AWSTemplateFormatVersion: "2010-09-09"
Description: |-
  Create ssh key pair
Resources:
  SampleKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: cfn-key
      KeyType: rsa
      # PublicKeyMaterial: String
      Tags:
        - Key: Name
          Value: cfn-key
